CREATE DEFINER=`testworkflow`@`%` PROCEDURE `CALCULAR`(
	IN `IN_IDPEDIDO` INT,
	IN `IN_FAMOFERTA` INT,
	IN `IN_FAMACUERDO` INT,
	IN `IN_CLIENTE` VARCHAR(10),
	IN `IN_DOCUMENTO` VARCHAR(10),
	IN `IN_CLAVE` VARCHAR(15),
	IN `IN_CANTIDAD` INT,
	IN `IN_PRECIOLP` INT,
	IN `IN_VENDEDOR` INT
)
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN
	DECLARE MINIMO_ACUERDO INT;
    DECLARE MINIMO_OFERTA INT;
    DECLARE CANTIDAD_OFERTA INT;
    DECLARE CANTIDAD_ACUERDO INT;
    DECLARE PRECIO_ACUERDO DECIMAL(25,6);	
    DECLARE PRECIO_OFERTA DECIMAL(25,6);
    DECLARE PRECIO_LP DECIMAL(25,6);
    DECLARE VALIDATION_COMISION INT;
    DECLARE VALIDATION_OFERTA INT;
	#variables de comisiones
    DECLARE VAR_COMISION_CODIGO VARCHAR(10);
    #VARIABLES DE OPERACION
    DECLARE VAR_ESTATUS VARCHAR(5);
    DECLARE VAR_CANTIDADES INT;
    DECLARE VAR_PORCENTAJE DECIMAL(25,6);
    DECLARE VAR_CLAVEVENDEDOR VARCHAR(10);
    DECLARE VAR_PORCENTAJE_F DECIMAL(25,6);
    DECLARE VAR_CLAVEVENDEDOR_F VARCHAR(10);
    DECLARE VAR_COMISION DECIMAL(25,6);
    DECLARE VAR_TOTAL DECIMAL(25,6);
 	#VARIABLES PARA PROUCTO
    DECLARE VAR_LODERA VARCHAR(100);
    DECLARE VALIDATION_ESQUEMA_OFERTA INT;
    DECLARE VALIDATION_ESQUEMA_ACUERDOS INT;
    DECLARE RESULT_ESQUEMA_OFERTA INTEGER;
    DECLARE RESULT_ESQUEMA_ACUERDOS INTEGER;

	
	SET VAR_ESTATUS = (SELECT ESTATUS FROM DETALLE_PEDIDO WHERE ID_DETALLE=IN_IDPEDIDO AND CLAVE=IN_CLAVE);
	SET VAR_CANTIDADES= (SELECT AGREGADOS FROM DETALLE_PEDIDO WHERE ID_DETALLE=IN_IDPEDIDO AND CLAVE=IN_CLAVE);
    SET RESULT_ESQUEMA_OFERTA = (SELECT COUNT(TIPO) AS CONTADOR FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='Acuerdo C.' AND ESTATUS='Activo');
    SET RESULT_ESQUEMA_ACUERDOS = (SELECT COUNT(TIPO) AS CONTADOR FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='Oferta' AND ESTATUS='Activo');

   #SUMA LA CANTIDA DEL GRUPO DE ACUERDOS
    IF IN_FAMACUERDO > 0 AND VAR_ESTATUS LIKE 'P' AND RESULT_ESQUEMA_OFERTA>0 THEN
	    
		 SET CANTIDAD_ACUERDO = (SELECT SUM(CANTIDAD) AS CANTIDAD FROM DETALLE_PEDIDO WHERE ID_DETALLE=IN_IDPEDIDO AND FAM_ACUERDO=IN_FAMACUERDO);
       SET VALIDATION_COMISION = 1;
       
       
    ELSEIF IN_FAMACUERDO > 0 AND VAR_ESTATUS LIKE 'PS' AND  VAR_CANTIDADES>0 AND RESULT_ESQUEMA_OFERTA>0 THEN
    
		 SET CANTIDAD_ACUERDO = (SELECT SUM(AGREGADOS) AS CANTIDAD FROM DETALLE_PEDIDO WHERE ID_DETALLE=IN_IDPEDIDO AND FAM_ACUERDO=IN_FAMACUERDO);
       SET VALIDATION_COMISION = 1;
       
    ELSEIF IN_FAMACUERDO > 0 AND VAR_ESTATUS LIKE 'AG' AND RESULT_ESQUEMA_OFERTA>0 THEN

		 SET CANTIDAD_ACUERDO = (SELECT SUM(CANTIDAD) AS CANTIDAD  FROM DETALLE_PEDIDO WHERE ID_DETALLE=IN_IDPEDIDO AND FAM_ACUERDO=IN_FAMACUERDO);
       SET VALIDATION_COMISION = 1;

	 ELSE
        SET VALIDATION_COMISION = 0;
        
    END IF;
   #SUMA LA CANTIDA DEL GRUPO DE OFERTA
    IF IN_FAMOFERTA > 0 AND VAR_ESTATUS LIKE 'P' AND RESULT_ESQUEMA_ACUERDOS>0 THEN
     
		  SET CANTIDAD_OFERTA = (SELECT SUM(CANTIDAD) AS CANTIDAD FROM DETALLE_PEDIDO WHERE ID_DETALLE=IN_IDPEDIDO AND FAM_OFERTA=IN_FAMOFERTA);
        SET VALIDATION_OFERTA = 1;

    ELSEIF IN_FAMOFERTA > 0 AND VAR_ESTATUS LIKE 'PS' AND  VAR_CANTIDADES>0 AND RESULT_ESQUEMA_ACUERDOS>0 THEN
    
		  SET CANTIDAD_OFERTA = (SELECT SUM(AGREGADOS) AS CANTIDAD FROM DETALLE_PEDIDO WHERE ID_DETALLE=IN_IDPEDIDO AND FAM_OFERTA=IN_FAMOFERTA);
        SET VALIDATION_OFERTA = 1;

    ELSEIF IN_FAMOFERTA > 0 AND VAR_ESTATUS LIKE 'AG' AND RESULT_ESQUEMA_ACUERDOS>0 THEN

		  SET CANTIDAD_OFERTA = (SELECT SUM(CANTIDAD) AS CANTIDAD FROM DETALLE_PEDIDO WHERE ID_DETALLE=IN_IDPEDIDO AND FAM_OFERTA=IN_FAMOFERTA);
        SET VALIDATION_OFERTA = 1;

    ELSE
        SET VALIDATION_OFERTA = 0;
    END IF;



    #BUSCA LA CANTIDAD MINIMA DE ACUERDOSCOMERCIALES DONDE DOCUMENTO,GRUPO Y CLIENTE COINCIDA;
   SET PRECIO_ACUERDO = (SELECT PRECIO FROM ACUERDOSCOMERCIAL WHERE FAM_ACUERDO=IN_FAMACUERDO AND CLAVE = IN_CLAVE);
   SET MINIMO_ACUERDO = (SELECT CANTIDAD FROM ACUERDOSCOMERCIAL WHERE FAM_ACUERDO=IN_FAMACUERDO AND CLAVE = IN_CLAVE);
    
    #BUSCA LA CANTIDAD MINIMA DE OFERTA DONDE GRUPO COINCIDA; 
   	SET PRECIO_OFERTA = (SELECT PRECIO FROM OFERTA WHERE GRUPO=IN_FAMOFERTA AND CLAVE=IN_CLAVE);
   	SET MINIMO_OFERTA = (SELECT MINIMA_CANTIDAD FROM OFERTA WHERE GRUPO=IN_FAMOFERTA AND CLAVE=IN_CLAVE);
    
    #BUSCA EL PRECIO DEL PRODUCTO DE LA LISTA DE PRECIO;
    SET PRECIO_LP = (SELECT PRECIO FROM LISTADEPRECIO WHERE CLAVE=IN_CLAVE AND FK_IDLP=IN_PRECIOLP);

    
    IF CANTIDAD_ACUERDO >= MINIMO_ACUERDO AND VALIDATION_COMISION > 0 THEN

        #VALIDACION DE DOCUMENTO
        IF IN_DOCUMENTO LIKE 'Factura' THEN
		
		  		SET VAR_PORCENTAJE_F = (SELECT COMISION_PORCENTAJE FROM COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='Acuerdo C.' AND ESTATUS='Activo'));
            SET VAR_CLAVEVENDEDOR_F = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='Acuerdo C.' AND ESTATUS='Activo'));
        
		  #CONTRAPARTE REMISION
        
		      SET VAR_PORCENTAJE = (SELECT COMISION_PORCENTAJE FROM COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Remision' AND TIPO='Acuerdo C.' AND ESTATUS='Activo'));
            SET VAR_CLAVEVENDEDOR = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Remision' AND TIPO='Acuerdo C.' AND ESTATUS='Activo'));
            
            SET VAR_TOTAL = TRUNCATE(PRECIO_ACUERDO * IN_CANTIDAD,6);
            #SET VAR_COMISION = VAR_TOTAL *(VAR_PORCENTAJE/100);
            
           	UPDATE DETALLE_PEDIDO SET PRECIO=TRUNCATE(PRECIO_ACUERDO,6), MONTO=VAR_TOTAL, ESTATUS_OFERTA='C/A',PORCENTAJE_F=VAR_PORCENTAJE_F, COMISION_F=VAR_CLAVEVENDEDOR_F,PORCENTAJE=VAR_PORCENTAJE,COMISION=VAR_CLAVEVENDEDOR WHERE CLIENTE=IN_CLIENTE AND ID_DETALLE=IN_IDPEDIDO AND FAM_ACUERDO=IN_FAMACUERDO;
            CALL LOOPAGREMENT(IN_IDPEDIDO,IN_DOCUMENTO,IN_FAMACUERDO);
         
         
        ELSEIF IN_DOCUMENTO LIKE 'Remision' THEN
      
				SET VAR_PORCENTAJE = (SELECT COMISION_PORCENTAJE FROM COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='Acuerdo C.' AND ESTATUS='Activo'));
            SET VAR_CLAVEVENDEDOR = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='Acuerdo C.' AND ESTATUS='Activo'));
		#CONTRAPARTE Factura
            SET VAR_PORCENTAJE_F = (SELECT COMISION_PORCENTAJE FROM COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Factura' AND TIPO='Acuerdo C.' AND ESTATUS='Activo'));
            SET VAR_CLAVEVENDEDOR_F = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Factura' AND TIPO='Acuerdo C.' AND ESTATUS='Activo'));
            
            SET VAR_TOTAL = TRUNCATE(PRECIO_ACUERDO * IN_CANTIDAD,6);
            #SET VAR_COMISION = VAR_TOTAL *(VAR_PORCENTAJE/100);
            
            UPDATE DETALLE_PEDIDO SET PRECIO=TRUNCATE(PRECIO_ACUERDO/1.16,6), PORCENTAJE=VAR_PORCENTAJE, MONTO=VAR_TOTAL, ESTATUS_OFERTA='C/A', COMISION=VAR_CLAVEVENDEDOR,PORCENTAJE_F=VAR_PORCENTAJE_F, COMISION_F=VAR_CLAVEVENDEDOR_F WHERE CLIENTE=IN_CLIENTE AND ID_DETALLE=IN_IDPEDIDO AND FAM_ACUERDO=IN_FAMACUERDO;
            CALL LOOPAGREMENT(IN_IDPEDIDO,IN_DOCUMENTO,IN_FAMACUERDO);
        		
        END IF;
    
        
    ELSEIF PRECIO_LP>PRECIO_OFERTA AND VALIDATION_OFERTA > 0 AND IN_VENDEDOR<21 THEN
		
        IF CANTIDAD_OFERTA >= MINIMO_OFERTA THEN 

                IF IN_DOCUMENTO LIKE 'Factura' THEN
                    SET VAR_LODERA = (SELECT DESCRIPCION FROM PRODUCTO WHERE CLAVE = IN_CLAVE);
                    SET VAR_LODERA = SUBSTRING(VAR_LODERA,1,6);
                      
                        IF IN_VENDEDOR < 14 AND VAR_LODERA LIKE 'LODERA' THEN
                            SET VAR_PORCENTAJE = (SELECT COMISION.COMISION_PORCENTAJE FROM COMISION WHERE CODIGO_COMISION='RFLOD');
                            SET VAR_CLAVEVENDEDOR ="RFLOD";

                            SET VAR_PORCENTAJE_F = (SELECT COMISION.COMISION_PORCENTAJE FROM COMISION WHERE CODIGO_COMISION='OFLOD');
                            SET VAR_CLAVEVENDEDOR_F ="OFLOD";
       
                        ELSE
                            SET VAR_PORCENTAJE = (SELECT COMISION_PORCENTAJE FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Remision' AND TIPO='Oferta' AND ESTATUS='Activo'));
                            SET VAR_CLAVEVENDEDOR = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Remision' AND TIPO='Oferta' AND ESTATUS='Activo'));
                             
                            SET VAR_PORCENTAJE_F = (SELECT COMISION_PORCENTAJE FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='Oferta' AND ESTATUS='Activo'));
                            SET VAR_CLAVEVENDEDOR_F = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='Oferta' AND ESTATUS='Activo'));                       

								END IF;
								
                            SET VAR_TOTAL = TRUNCATE(PRECIO_OFERTA * IN_CANTIDAD,6);
                            UPDATE DETALLE_PEDIDO SET PRECIO=TRUNCATE(PRECIO_OFERTA,6), PORCENTAJE=VAR_PORCENTAJE, MONTO=VAR_TOTAL, ESTATUS_OFERTA='C/O', COMISION=VAR_CLAVEVENDEDOR,PORCENTAJE_F=VAR_PORCENTAJE_F, COMISION_F=VAR_CLAVEVENDEDOR_F WHERE CLIENTE=IN_CLIENTE AND ID_DETALLE=IN_IDPEDIDO AND FAM_OFERTA=IN_FAMOFERTA;
               				CALL LOOPSALE(IN_IDPEDIDO,IN_DOCUMENTO,IN_FAMOFERTA);
               				 
                ELSEIF IN_DOCUMENTO LIKE 'Remision' THEN

                    SET VAR_LODERA = (SELECT DESCRIPCION FROM PRODUCTO WHERE CLAVE = IN_CLAVE);
                    SET VAR_LODERA = SUBSTRING(VAR_LODERA,1,6);
                    
                        IF IN_VENDEDOR < 14 AND VAR_LODERA LIKE 'LODERA' THEN

                            SET VAR_PORCENTAJE = (SELECT COMISION.COMISION_PORCENTAJE FROM COMISION WHERE CODIGO_COMISION='RFLOD');
                            SET VAR_CLAVEVENDEDOR ="RFLOD";

                            SET VAR_PORCENTAJE_F = (SELECT COMISION.COMISION_PORCENTAJE FROM COMISION WHERE CODIGO_COMISION='OFLOD');
                            SET VAR_CLAVEVENDEDOR_F ="OFLOD";
                        ELSE

                            SET VAR_PORCENTAJE = (SELECT COMISION_PORCENTAJE FROM 
                            COMISION WHERE COMISION.CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='Oferta' AND ESTATUS='Activo'));
                            SET VAR_CLAVEVENDEDOR = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='Oferta' AND ESTATUS='Activo'));
                            
                            SET VAR_PORCENTAJE_F = (SELECT COMISION_PORCENTAJE FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Factura' AND TIPO='Oferta' AND ESTATUS='Activo'));
                            SET VAR_CLAVEVENDEDOR_F = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Factura' AND TIPO='Oferta' AND ESTATUS='Activo')); 
                        END IF;

                    SET VAR_TOTAL = TRUNCATE(PRECIO_OFERTA * IN_CANTIDAD,6);
                    UPDATE DETALLE_PEDIDO SET PRECIO=TRUNCATE(PRECIO_OFERTA/1.16,6), PORCENTAJE=VAR_PORCENTAJE, MONTO=VAR_TOTAL, ESTATUS_OFERTA='C/O', COMISION=VAR_CLAVEVENDEDOR, PORCENTAJE_F=VAR_PORCENTAJE_F, COMISION_F=VAR_CLAVEVENDEDOR_F WHERE CLIENTE=IN_CLIENTE AND ID_DETALLE=IN_IDPEDIDO AND FAM_OFERTA=IN_FAMOFERTA;
                    CALL LOOPSALE(IN_IDPEDIDO,IN_DOCUMENTO,IN_FAMOFERTA);

                END IF;
                
        ELSE       
        
            IF IN_DOCUMENTO LIKE 'Factura' THEN

					 SET VAR_PORCENTAJE = (SELECT COMISION_PORCENTAJE FROM 
                                    COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA 
												WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Remision' AND TIPO='L. Precios' AND ESTATUS='Activo'));
                SET VAR_CLAVEVENDEDOR = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Remision' AND TIPO='L. Precios' AND ESTATUS='Activo'));
                
                SET VAR_PORCENTAJE_F = (SELECT COMISION_PORCENTAJE FROM 
                                    COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA 
												WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='L. Precios' AND ESTATUS='Activo'));
                SET VAR_CLAVEVENDEDOR_F = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='L. Precios' AND ESTATUS='Activo'));
                
                SET VAR_TOTAL = TRUNCATE(PRECIO_LP * IN_CANTIDAD,6);
                UPDATE DETALLE_PEDIDO SET PRECIO=TRUNCATE(PRECIO_LP,6), PORCENTAJE=VAR_PORCENTAJE, MONTO=VAR_TOTAL, ESTATUS_OFERTA='S/O', COMISION=VAR_CLAVEVENDEDOR, PORCENTAJE_F=VAR_PORCENTAJE_F, COMISION_F=VAR_CLAVEVENDEDOR_F 
					 WHERE CLIENTE=IN_CLIENTE AND ID_DETALLE=IN_IDPEDIDO AND CLAVE=IN_CLAVE;

            ELSEIF IN_DOCUMENTO LIKE 'Remision' THEN
                
					 SET VAR_PORCENTAJE = (SELECT COMISION_PORCENTAJE FROM
                                    COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA 
												WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='L. Precios' AND ESTATUS='Activo'));
                SET VAR_CLAVEVENDEDOR = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='L. Precios' AND ESTATUS='Activo'));
                
                SET VAR_PORCENTAJE_F = (SELECT COMISION_PORCENTAJE FROM 
                                    COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA 
												WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Factura' AND TIPO='L. Precios' AND ESTATUS='Activo'));
                SET VAR_CLAVEVENDEDOR_F = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Factura' AND TIPO='L. Precios' AND ESTATUS='Activo'));
                
                SET VAR_TOTAL = TRUNCATE(PRECIO_LP,6) * IN_CANTIDAD;
                
                UPDATE DETALLE_PEDIDO SET PRECIO=TRUNCATE(PRECIO_LP,6), MONTO=VAR_TOTAL, PORCENTAJE=VAR_PORCENTAJE, ESTATUS_OFERTA='S/O', COMISION=VAR_CLAVEVENDEDOR, PORCENTAJE_F=VAR_PORCENTAJE_F, COMISION_F=VAR_CLAVEVENDEDOR_F
					 WHERE CLIENTE=IN_CLIENTE AND ID_DETALLE=IN_IDPEDIDO AND CLAVE=IN_CLAVE;
                
            END IF;
        END IF;  

    ELSE

           IF IN_DOCUMENTO LIKE 'Factura' THEN
           
					 SET VAR_PORCENTAJE = (SELECT COMISION_PORCENTAJE FROM 
                                    COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA 
												WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Remision' AND TIPO='L. Precios' AND ESTATUS='Activo'));
                SET VAR_CLAVEVENDEDOR = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Remision' AND TIPO='L. Precios' AND ESTATUS='Activo'));
                
                SET VAR_PORCENTAJE_F = (SELECT COMISION_PORCENTAJE FROM 
                                    COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA 
												WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='L. Precios' AND ESTATUS='Activo'));
                SET VAR_CLAVEVENDEDOR_F = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='L. Precios' AND ESTATUS='Activo'));
                

                SET VAR_TOTAL = TRUNCATE(PRECIO_LP * IN_CANTIDAD,6);
                UPDATE DETALLE_PEDIDO SET PRECIO=TRUNCATE(PRECIO_LP,6), PORCENTAJE=VAR_PORCENTAJE,MONTO=VAR_TOTAL, ESTATUS_OFERTA='S/O', COMISION=VAR_CLAVEVENDEDOR,PORCENTAJE_F=VAR_PORCENTAJE_F, COMISION_F=VAR_CLAVEVENDEDOR_F
					 WHERE CLIENTE=IN_CLIENTE AND ID_DETALLE=IN_IDPEDIDO AND CLAVE=IN_CLAVE;

            ELSEIF IN_DOCUMENTO LIKE 'Remision' THEN

					 SET VAR_PORCENTAJE = (SELECT COMISION_PORCENTAJE FROM
                                    COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA
												WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='L. Precios' AND ESTATUS='Activo'));
                SET VAR_CLAVEVENDEDOR = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO=IN_DOCUMENTO AND TIPO='L. Precios' AND ESTATUS='Activo'));
                
                SET VAR_PORCENTAJE_F = (SELECT COMISION_PORCENTAJE FROM
                                    COMISION WHERE CODIGO_COMISION=(SELECT COMISION_ESQUEMA FROM ESQUEMA
												WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Factura' AND TIPO='L. Precios' AND ESTATUS='Activo'));
                SET VAR_CLAVEVENDEDOR_f = (SELECT CODIGO_COMISION FROM COMISION WHERE CODIGO_COMISION=
                            (SELECT COMISION_ESQUEMA FROM ESQUEMA WHERE CLIENTE=IN_CLIENTE AND DOCUMENTO='Factura' AND TIPO='L. Precios' AND ESTATUS='Activo'));
                
                SET VAR_TOTAL = TRUNCATE(PRECIO_LP,6) * IN_CANTIDAD;
                
                UPDATE DETALLE_PEDIDO SET PRECIO=TRUNCATE(PRECIO_LP,6), MONTO=VAR_TOTAL, PORCENTAJE=VAR_PORCENTAJE, ESTATUS_OFERTA='S/O', COMISION=VAR_CLAVEVENDEDOR,PORCENTAJE_F=VAR_PORCENTAJE_F, COMISION_F=VAR_CLAVEVENDEDOR_F
					 WHERE CLIENTE=IN_CLIENTE AND ID_DETALLE=IN_IDPEDIDO AND CLAVE=IN_CLAVE;
                
            END IF;
    END IF;
END