BEGIN 
	DECLARE ROW_ORDER INT;
	DECLARE ID_ORDER INT;
	SELECT COUNT(ID) INTO ROW_ORDER FROM PEDIDO WHERE ESTATUS='P' AND CLIENTE = IN_CLIENTE AND FECHA = STR_TO_DATE(NOW(),'%Y-%m-%d') AND DOCUMENTO = IN_DOCUMENTO;		
		IF ROW_ORDER = 0 THEN	
			INSERT INTO PEDIDO(CLIENTE, VENDEDOR, FECHA, HORA, DOCUMENTO, ESTATUS, OBSERVACION,FOLIO,USUARIO)
	      VALUES(IN_CLIENTE,IN_VENDEDOR,STR_TO_DATE(NOW(),'%Y-%m-%d'),IN_HORA,IN_DOCUMENTO,IN_ESTATUS,IN_OBSERVACION,IN_FOLIO,IN_USUARIO);
	      
			SELECT ID INTO ID_ORDER FROM PEDIDO WHERE CLIENTE = IN_CLIENTE AND FECHA = STR_TO_DATE(NOW(),'%Y-%m-%d') AND DOCUMENTO = IN_DOCUMENTO AND ESTATUS='P';
			CALL GENERATE_FILE(ID_ORDER);
			SELECT CONCAT_WS('/',ID_ORDER,0);
			
		ELSE
			SELECT ID INTO ID_ORDER FROM PEDIDO WHERE CLIENTE = IN_CLIENTE AND FECHA = STR_TO_DATE(NOW(),'%Y-%m-%d') AND DOCUMENTO = IN_DOCUMENTO AND ESTATUS='P';
			SELECT CONCAT_WS('/',ID_ORDER,1);
		END IF;
END