DROP PROCEDURE IF EXISTS ADD_ITEM_BACKORDER;

DELIMITER $$
CREATE PROCEDURE ADD_ITEM_BACKORDER(
	IN VAR_FOLIO VARCHAR(90),
	IN VAR_CLAVE VARCHAR(45),
	IN VAR_CANTIDAD INT,
	IN VAR_DESC VARCHAR(90),
	IN VAR_PRECIO DECIMAL(20,6),
	IN VAR_RESTRINCCION VARCHAR(45),
	IN VAR_ESTATUS_OFERTA VARCHAR(45),
	IN VAR_FAM_OFERTA VARCHAR(45),
	IN VAR_TOTAL VARCHAR(45),
	IN VAR_ID_DETALLE VARCHAR(45)			
	
)
BEGIN
	DECLARE result INT;
	
	SET result  = (SELECT COUNT (id) FROM detalle_pedido WHERE clave = VAR_CLAVE AND id_detalle =  VAR_ID_DETALLE);
	
	IF  result  = 0 THEN 
		INSERT INTO detalle_pedido()VALUES();
	ELSE
		SELECT * FROM detalle_pedido;
	END IF;
END